var mongoose = require('mongoose'); //load the mongoose module, ORM for MongoDB
var User = require("../models/user.js").User;

var db_name = "MeetingMagic";

mongoose.connect('mongodb://localhost/' + db_name); //connect to the database on 'localhost'

function read_user(uname, pwd) {
  User.findOne({ username: uname, password: pwd }, function(err, user) {
    if (user) {
      console.log("user " + user.username + " exists")
    }
    else {
      console.log("user doesn't exist")
    }
  })
}

function write_user(uname, pwd, foodPrefs) {
  //create new user based on User db model
  var user1 = new User({
    id: new mongoose.Types.ObjectId, //autogenerated by MongoDB
    username: uname,
    password: pwd,
    food_prefs: foodPrefs //This is an array of Strings
  });

  //save the user to the db
  user1.save(function (err, userObj) {
    if (err) {
      console.log(err);
    }
    else {
      console.log('Saved successfully: ', userObj);
    }
  });
}

//write_user("noahw", "123noah123", ["Pizza", "Indian", "Sushi"]);
//read_user("noahw", "123noah123");
