var mongoose = require('mongoose'); //load the mongoose module, ORM for MongoDB
var User = require("../models/user.js").User;

// debug.js
var debug = require("./debug/debug.js");
dlog = debug.dlog;
def_opts = {
  id: "mongodb",
  isError: false
}

var db_name = "MeetingMagic";

mongoose.connect('mongodb://localhost/' + db_name); //connect to the database on 'localhost'

function read_user(uname, pwd) {
  User.findOne({ username: uname, password: pwd }, function(err, user) {
    if (err) {
      dlog("failed reading user " + uname, {id: "mongodb", isError: true, errMsg: err});
    }
    else {
      dlog("user " + user.username + " exists", def_opts);
    }
  })
}

function write_user(uname, pwd, foodPrefs) {
  //create new user based on User db model
  var user1 = new User({
    id: new mongoose.Types.ObjectId, //autogenerated by MongoDB
    username: uname,
    password: pwd,
    food_prefs: foodPrefs //This is an array of Strings
  });

  //save the user to the db
  user1.save(function (err, userObj) {
    if (err) {
      dlog("failed writing user " + userObj.username, {id: "mongodb", isError: true, errMsg: err});
    }
    else {
      console.log('Saved successfully: ', userObj);
    }
  });
}

write_user("test1", "123noah123", ["Pizza", "Indian", "Sushi"]);
read_user("test2", "123noah123");
